### ISSUE TITLE
No titles in navigation bar

### ISSUE THREAD

**Issue by dblanchet** [Orange-OpenSource/orange-trust-badge-ios#2]
On iPhone, the various views (main, perms, terms, etc.) do not show any titles in navigation bar. Am I missing something?

**Comment by marcbeaudoin** [comment]
Check if your project contains the badge Localizable.strings file or if you've correctly overriden it.

**Comment by dblanchet** [comment]
Both `fr` and `en` Localizable.strings are present in the framework bundle used in our app.

Please note that other string resources seem to be reachable, as the graphical component is properly displayed. We even managed to override some of them.
