### ISSUE TITLE
Switching between dark / light mode not taken in account

### ISSUE THREAD

**Issue by patmonfort** [Orange-OpenSource/orange-trust-badge-ios#34]
1. Start OTB main screen that displays "données accessibles par l'application / Données d'usage de l'application / L'engagement d'Orange".
2.tap "L'engagement d'Orange -> a screen is displayed in light or dark mode depending on the current device configuration
3. change dynamically the dark / light mode
4 Result : the content is not correctly refreshed, only Headers of section is visible
We expect the color of the text to change from dark to light for example when switiching from light mode to dark mode.

**Comment by marcbeaudoin** [comment]
Fixed in 1.1.9
